spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pets_db
    username: postgres
    password: parol #поставить верный
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
